apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-team-turtle
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster: dev
          - cluster: stage
          - cluster: prod
      - list:
          elements:
          - project: team-turtle
  template:
    metadata:
      name: 'guestbook-{{project}}-{{cluster}}'
    spec:
      project: '{{project}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/dhpup/argocd-project-team-turtle.git
        targetRevision: HEAD
        path: configs/guestbook/env/{{cluster}}
      destination:
        name: 'mac2'
        namespace: 'guestbook-{{cluster}}-{{project}}'

